import { DateTimeTool } from "./tools/DateTimeTool.js";
import { CalculatorTool } from "./tools/CalculatorTool.js";
import { LocalStorageTool } from "./tools/LocalStorageTool.js";
import { ClipboardTool } from "./tools/ClipboardTool.js";
import { GeolocationTool } from "./tools/GeolocationTool.js";
import { NotificationTool } from "./tools/NotificationTool.js";
import { BrowserInfoTool } from "./tools/BrowserInfoTool.js";
import { ProviderHealthCheckTool } from "./tools/ProviderHealthCheckTool.js";
import { OllamaModelsTool } from "./tools/OllamaModelsTool.js";
import { MemorySearchTool } from "./tools/MemorySearchTool.js";
import { ClipboardWriteTool } from "./tools/ClipboardWriteTool.js";
import { DownloadFileTool } from "./tools/DownloadFileTool.js";
import { JsonValidatorTool } from "./tools/JsonValidatorTool.js";
import { ContextPreviewTool } from "./tools/ContextPreviewTool.js";
import { HtmlPreviewTool } from "./tools/HtmlPreviewTool.js";
import { PageInfoTool } from "./tools/PageInfoTool.js";
import { TextFormatterTool } from "./tools/TextFormatterTool.js";
import { UuidGeneratorTool } from "./tools/UuidGeneratorTool.js";
import { TokenEstimatorTool } from "./tools/TokenEstimatorTool.js";
import { RegexTesterTool } from "./tools/RegexTesterTool.js";
import { MemoryCreateTool } from "./tools/MemoryCreateTool.js";
import { MemoryUpdateTool } from "./tools/MemoryUpdateTool.js";
import { MemoryDeleteTool } from "./tools/MemoryDeleteTool.js";
import { ConversationExportTool } from "./tools/ConversationExportTool.js";
import { SettingsExportTool } from "./tools/SettingsExportTool.js";
import { LocalStorageInspectorTool } from "./tools/LocalStorageInspectorTool.js";
import { FileImportTool } from "./tools/FileImportTool.js";
import { MarkdownToHtmlTool } from "./tools/MarkdownToHtmlTool.js";
import { CsvParserTool } from "./tools/CsvParserTool.js";
import { TableFormatterTool } from "./tools/TableFormatterTool.js";
import { SpeechSynthesisTool } from "./tools/SpeechSynthesisTool.js";
import { SpeechRecognitionTool } from "./tools/SpeechRecognitionTool.js";
import { CameraCheckTool } from "./tools/CameraCheckTool.js";
import { NetworkStatusTool } from "./tools/NetworkStatusTool.js";
import { PromptDebuggerTool } from "./tools/PromptDebuggerTool.js";
import { MemoryOptimizerRunTool } from "./tools/MemoryOptimizerRunTool.js";
import { ToolListTool } from "./tools/ToolListTool.js";

export function registerBrowserTools(toolsService, repository, dependencies = {}) {
  toolsService.register(new DateTimeTool());
  toolsService.register(new CalculatorTool());
  toolsService.register(new BrowserInfoTool());
  toolsService.register(new PageInfoTool());
  toolsService.register(new TextFormatterTool());
  toolsService.register(new UuidGeneratorTool());
  toolsService.register(new TokenEstimatorTool());
  toolsService.register(new RegexTesterTool());
  toolsService.register(new ClipboardTool());
  toolsService.register(new ClipboardWriteTool());
  toolsService.register(new GeolocationTool());
  toolsService.register(new NotificationTool());
  toolsService.register(new LocalStorageTool(repository));
  toolsService.register(new ProviderHealthCheckTool(dependencies));
  toolsService.register(new OllamaModelsTool(dependencies));
  toolsService.register(new MemorySearchTool(dependencies));
  toolsService.register(new MemoryCreateTool(dependencies));
  toolsService.register(new MemoryUpdateTool(dependencies));
  toolsService.register(new MemoryDeleteTool(dependencies));
  toolsService.register(new ConversationExportTool(dependencies));
  toolsService.register(new SettingsExportTool(dependencies));
  toolsService.register(new DownloadFileTool());
  toolsService.register(new JsonValidatorTool());
  toolsService.register(new ContextPreviewTool({ ...dependencies, toolsService }));
  toolsService.register(new HtmlPreviewTool());
  toolsService.register(new LocalStorageInspectorTool(repository));
  toolsService.register(new FileImportTool());
  toolsService.register(new MarkdownToHtmlTool());
  toolsService.register(new CsvParserTool());
  toolsService.register(new TableFormatterTool());
  toolsService.register(new SpeechSynthesisTool());
  toolsService.register(new SpeechRecognitionTool());
  toolsService.register(new CameraCheckTool());
  toolsService.register(new NetworkStatusTool());
  toolsService.register(new PromptDebuggerTool());
  toolsService.register(new MemoryOptimizerRunTool(dependencies));
  toolsService.register(new ToolListTool({ toolsService }));
}
